spring:
  application:
    name: EnterpriseResumptionReview


  # DataSource Config
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/enterprise_resumption_review?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: 2EF05645DA61B8A6C8624B734E0ABA6A
    password: 2EF05645DA61B8A6C8624B734E0ABA6A

  # flyway
  flyway:
    #schemas: public
    baseline-on-migrate: true
    table: schema_version

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
#      location: D:\\

# mybatis plus config
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.dyoon.review.**.entity
  global-config:
    banner: off
    # 是否缓存SQL解析
  #    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.dyoon.review.domain: debug
